name: rag_frontend_and_management
description: "PakConstitution AI - Constitutional Research App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  sqflite: ^2.3.3
  path: ^1.9.0
  shared_preferences: ^2.3.2
  google_fonts: ^6.2.1
  http: ^1.2.2
  flutter_markdown: ^0.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
  windows:
    generate: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#111113"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/